# Generated by Django 5.1.3 on 2024-11-30 21:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Client name')),
                ('username', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Client username')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Points')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=10, unique=True, verbose_name='License plate')),
                ('vin', models.CharField(max_length=17, verbose_name='VIN')),
                ('brand', models.CharField(choices=[('AUDI', 'Audi'), ('BMW', 'BMW'), ('MERCEDES', 'Mercedes-Benz'), ('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('FORD', 'Ford'), ('OPEL', 'Opel'), ('VOLKSWAGEN', 'Volkswagen'), ('NISSAN', 'Nissan'), ('HYUNDAI', 'Hyundai'), ('KIA', 'Kia'), ('PEUGEOT', 'Peugeot'), ('RENAULT', 'Renault'), ('CHEVROLET', 'Chevrolet'), ('JEEP', 'Jeep'), ('SUBARU', 'Subaru'), ('MAZDA', 'Mazda'), ('LAND_ROVER', 'Land Rover'), ('VOLVO', 'Volvo'), ('PORSCHE', 'Porsche'), ('LEXUS', 'Lexus'), ('JAGUAR', 'Jaguar'), ('FIAT', 'Fiat'), ('ALFA_ROMEO', 'Alfa Romeo'), ('MITSUBISHI', 'Mitsubishi'), ('SUZUKI', 'Suzuki'), ('LADA', 'Lada'), ('OTHER', 'Other')], verbose_name='Brand')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year')),
                ('first_visit', models.DateField(auto_now_add=True, verbose_name='First visit')),
                ('car_notes', models.TextField(blank=True, null=True, verbose_name='Notes about car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]
